const router = require("express").Router();
const attendanceRoutes = require("./attendance/index");
const departmentRoutes = require("./department/index");
const employeesRoutes = require("./employees/index");
const businessRoutes = require("./business");
const loginRoutes = require("./users/index");
const shiftRoutes = require("./shifts/");
const locationRoutes = require("./locations/index");
const employeeLocationRoutes = require("./employee_locations");
const rolesRoutes = require("./roles");
const countriesRoutes = require("./countries");
const verifyAuth = require("../middleware/authentication/index");

router.use("/attendance", verifyAuth, attendanceRoutes);
router.use("/departments", verifyAuth, departmentRoutes);
router.use("/employees", verifyAuth, employeesRoutes);
router.use("/shift", verifyAuth, shiftRoutes);
router.use("/roles", verifyAuth, rolesRoutes);
router.use("/locations", verifyAuth, locationRoutes);
router.use("/employee-locations", verifyAuth, employeeLocationRoutes);
router.use("/business", businessRoutes);
router.use("/user", loginRoutes);
router.use("/countries", countriesRoutes);
module.exports = router;
